version: '3'
services:
  app:
    image: node-cart:latest
    container_name: node-cart-main
    ports:
      - 3000:3000
    # working_dir: /app
    # volumes:
    #   - ./:/app
    # environment:
    #   MYSQL_HOST: localhost
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: 
    #   MYSQL_DB: test
#   mongo:
#     image: mongo
#     container_name: app_mongo
#     restart: always
#     ports:
#       - 27017:27017
#     volumes:
#       - ~/mongo:/data/db
# volumes:
#   mongodb: